Sign in
touredri/blog pull request #11
Opened 2023-07-27 23:21 UTC by touredri

- [ ] Used devise 
- [ ] Login page 
- [ ] registration page
- [ ] email verification

2023-07-27 23:38 UTC, Omar-Muhamad reviewed
# Invalid ❌

Hi team,

#### While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

#### Your Code Review Request is marked as invalid for this reason:

- [ ] Some linters checks are not passed. Please make sure that all checks are passing and green.

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **Does not count** into the code reviews limit._

2023-07-28 01:19 UTC, julie-ify requested changes
## Hi @touredri and @mercymugambi,

Good job so far!

## Highlights!
- Good feature branch name ✔️ 
- No linter errors ✔️ 
- Descriptive pull request ✔️ 
- Descriptive commit messages ✔️ 
- Good code organization and working app ✔️
- Descriptive README ✔️ 

Hello ✋, you have done well reaching this point of the milestone 🤝 . But there are some issues that you still need to work on to go to the next project but you are almost there!

# Status: Required Changes ♻️⛔️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread and tag me `@julie-ify` if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-07-28 01:19 UTC, julie-ify commented on app/controllers/users_controller.rb
> +  before_action :authenticate_user!
- [ ] **[OPTIONAL]** I believe it would be more suitable to move this helper method call to the application controller, instead of leaving it on the users' controller. If you move it to the application controller, the authentication will happen across all controllers.

2023-07-28 01:19 UTC, julie-ify commented on Gemfile
> +# gem 'bootsnap', require: false
- [ ] Kindly uncomment this gem. I cannot set up your database and run your app without it.

2023-07-28 05:56 UTC, touredri commented on app/controllers/users_controller.rb
> +  before_action :authenticate_user!
Ok

2023-07-28 05:57 UTC, touredri commented on Gemfile
> +# gem 'bootsnap', require: false
@julie-ify  Or mine work without it!

2023-07-28 06:21 UTC, Ibizugbe approved these changes
Hi @touredri 👋🏼👋🏼👋🏼👋🏼, 

![approved](https://github.com/touredri/blog/assets/64643995/e5e743b6-7b2b-468e-84c9-e09a1d91e349)


Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## Highlights✅✅✅

- [x] Commented piece of code has been uncommented as requested by the previous reviewer👍🏼.

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-07-28 06:43 UTC, merged